export const BOMBER_TAGS = [
    "Bomber vero", 
    "Più forte con Excel",
    "Se sbaglio è colpa del dirigente",
    "Se giochiamo dopo le 23 sono contento",
    "W la Pres",
    "Zucchetti non va",
    "Il nuovo Schick",
    "No porta plz",
    "Sono giapponese",
    "Uomo spogliatoio", 
    "Terzo tempo MVP", 
    "Polmoni d'acciaio", 
    "Piede fatato", 
    "Il Muro", 
    "Gattuso me spiccia casa", 
    "Rigore è quando arbitro fischia", 
    "Zero tituli", 
    "Lo Special One", 
    "Sempre rotto",
    "Il decimo a calcetto",
    "Social Media Manager", 
    "Capitano morale",
    "Finto infortunato",
    "Vado a farmi la doccia"
];