// Testo del Regolamento Ufficiale ASI 2026/2027 e dell'Allegato n.1,
// estratto dai PDF in public/docs. Blocchi: "## " sottotitolo, "- " punto elenco, altrimenti paragrafo.

export type RegolamentoSection = {
  id: string
  label: string
  title: string
  blocks: string[]
}

export const REGOLAMENTO_PDF = "/docs/regolamento-2026-2027.pdf"

export const REGOLAMENTO_SECTIONS: RegolamentoSection[] = [
  {
    "id": "art-1",
    "label": "Art. 1",
    "title": "Organizzazione e scopo",
    "blocks": [
      "È indetto, sotto l’egida dell’Ente di Promozione Sportiva A.S.I. – Associazioni Sportive e Sociali Italiane, il Campionato a carattere prettamente amatoriale e ricreativo.",
      "Le gare del Campionato avranno, salvo eventuali esigenze connesse alla predisposizione e alla definizione del calendario ufficiale, cadenza bisettimanale e saranno disputate secondo il calendario predisposto e successivamente comunicato dal Comitato Organizzatore.",
      "Le gare si svolgeranno presso gli impianti sportivi individuati e messi a disposizione delle squadre partecipanti al Campionato e saranno dirette da Direttori di Gara appartenenti all’A.S.I., secondo le modalità organizzative previste dall’Ente.",
      "Tutti gli aspetti relativi alle procedure di affiliazione e tesseramento, nonché gli ulteriori adempimenti amministrativi, assicurativi, arbitrali e di Giustizia Sportiva, sono demandati, per quanto di rispettiva competenza, all’E.P.S. A.S.I. – Associazioni Sportive e Sociali Italiane, Comitato Provinciale di Roma, con sede in Via Adolfo Ravà n. 106 – Roma.",
      "## COMUNICAZIONI UFFICIALI",
      "Tutte le comunicazioni, richieste, istanze e documentazioni relative al Campionato dovranno essere trasmesse agli indirizzi di posta elettronica ufficiali:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "## RIUNIONI E INIZIATIVE ORGANIZZATIVE",
      "Alle riunioni, agli incontri e alle eventuali cene organizzate nell’ambito delle attività della struttura organizzativa potranno partecipare i rappresentanti delle squadre regolarmente iscritte al Campionato, unitamente ai soggetti designati dall’Ente di Promozione Sportiva A.S.I. e agli eventuali ulteriori invitati dal Comitato Organizzatore.",
      "La partecipazione di eventuali ospiti, accompagnatori o ulteriori dirigenti rispetto al rappresentante ufficiale della squadra sarà consentita a titolo personale e con oneri a carico degli stessi, salvo diversa disposizione del Comitato Organizzatore.",
      "## DATI PER I VERSAMENTI",
      "Per i versamenti eventualmente dovuti secondo le modalità e le scadenze previste dal presente Regolamento:",
      "IBAN: IT92G0306909606100000112025 Istituto bancario: Intesa Sanpaolo"
    ]
  },
  {
    "id": "art-2",
    "label": "Art. 2",
    "title": "Partecipazione ai campionati",
    "blocks": [
      "Il Campionato è riservato esclusivamente alle squadre che presentino regolare domanda di partecipazione, perfezionino l’affiliazione all’A.S.I. e dispongano di un organico composto da calciatori regolarmente tesserati A.S.I. per la medesima società sportiva.",
      "Non sarà pertanto consentita la partecipazione di calciatori tesserati A.S.I. per società diverse da quella rappresentata nel Campionato, salvo eventuali deroghe espressamente previste dalle normative e dai regolamenti A.S.I. vigenti.",
      "## COMUNICAZIONI TRAMITE GRUPPO WHATSAPP",
      "Ai fini di una più efficace gestione e organizzazione delle attività connesse al Campionato, i rappresentanti delle singole squadre saranno inseriti in un apposito gruppo WhatsApp ufficiale.",
      "Per ciascuna squadra potranno essere inseriti nel gruppo un massimo di due Dirigenti.",
      "Ciascuna squadra dovrà tuttavia individuare un solo Dirigente Responsabile, che assumerà il ruolo di referente ufficiale e portavoce della società nei rapporti con il Comitato Organizzatore.",
      "Il nominativo del Dirigente Responsabile dovrà essere comunicato al Comitato Organizzatore all’inizio del Campionato e sarà considerato il referente ufficiale della squadra per tutte le comunicazioni organizzative e regolamentari.",
      "Il Dirigente Responsabile potrà essere sostituito nel corso della stagione esclusivamente previa comunicazione formale effettuata tramite posta elettronica agli indirizzi indicati nel presente Regolamento.",
      "La sostituzione dovrà essere altresì comunicata nel gruppo WhatsApp ufficiale, al fine di consentire il tempestivo aggiornamento dei riferimenti organizzativi della squadra."
    ]
  },
  {
    "id": "art-3",
    "label": "Art. 3",
    "title": "Procedure di iscrizione",
    "blocks": [
      "## DIRIGENTE RESPONSABILE E ADEMPIMENTI DELLE SQUADRE",
      "Ogni squadra partecipante al Campionato dovrà essere rappresentata da almeno un Dirigente Responsabile, il quale costituirà il referente ufficiale della società nei rapporti con il Comitato Organizzatore e con l’A.S.I. – Comitato Provinciale di Roma.",
      "Il Dirigente Responsabile è tenuto ad adempiere ai seguenti obblighi:",
      "## A) ADESIONE E ACCETTAZIONE DEL REGOLAMENTO",
      "Comunicare la preventiva e definitiva adesione della squadra all’Organizzazione entro e non oltre il termine indicato nell’Allegato al presente Regolamento, provvedendo a sottoscrivere per accettazione il presente Regolamento e a trasmetterne la relativa pagina di accettazione ai seguenti indirizzi di posta elettronica:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "La sottoscrizione e la trasmissione del Regolamento costituiscono condizione necessaria per il perfezionamento dell’adesione al Campionato.",
      "## B) AFFILIAZIONE ALL’A.S.I.",
      "Provvedere agli adempimenti necessari per l’affiliazione o riaffiliazione della società all’Ente di Promozione Sportiva A.S.I., mediante compilazione dell’apposito Modulo 1 – Affiliazione/Riaffiliazione e presentazione della documentazione richiesta.",
      "La quota di affiliazione è stabilita in € 70,00 per ciascun anno solare, salvo eventuali variazioni deliberate dall’Ente competente.",
      "Per il primo anno di affiliazione, la validità della stessa decorrerà secondo le modalità e i termini stabiliti dall’A.S.I. e dalla normativa vigente.",
      "## C) DOMANDA DI ISCRIZIONE AL CAMPIONATO",
      "Presentare la domanda di iscrizione alla manifestazione, redatta sull’apposito modulo, entro e non oltre il 25 settembre 2026, trasmettendola all’A.S.I. – Comitato Provinciale di Roma, all’indirizzo:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "La domanda dovrà essere debitamente compilata, sottoscritta e corredata di tutta la documentazione e degli allegati richiesti dal Comitato Organizzatore.",
      "## D) INDICAZIONE DELL’IMPIANTO SPORTIVO",
      "La domanda di iscrizione dovrà contenere, a pena di incompletezza della procedura, l’indicazione dell’impianto sportivo individuato quale campo di gioco casalingo, presso il quale la squadra disputerà le gare interne, salvo successive variazioni autorizzate dal Comitato Organizzatore.",
      "## E) TESSERAMENTO DEI CALCIATORI",
      "Provvedere al regolare tesseramento dei singoli calciatori per la propria società o associazione presso gli uffici competenti dell’A.S.I. – Comitato Provinciale di Roma, in ogni caso prima dell’inizio della competizione.",
      "Il Dirigente Responsabile dovrà inoltre trasmettere la relativa lista dei calciatori regolarmente tesserati all’indirizzo di posta elettronica:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "La partecipazione alle gare sarà consentita esclusivamente ai calciatori regolarmente tesserati e inseriti nella documentazione prevista dal presente Regolamento.",
      "## F) ACCETTAZIONE DEL REGOLAMENTO",
      "Con la comunicazione/sottoscrizione di adesione e con il deposito della domanda di iscrizione, la squadra, la società e/o l’associazione partecipante dichiarano di aver preso visione del presente Regolamento e di accettarne integralmente e senza riserva tutte le disposizioni, comprese le norme relative agli obblighi organizzativi, amministrativi, disciplinari e alle eventuali sanzioni previste.",
      "I termini e le scadenze indicati nel presente Regolamento sono da considerarsi perentori, in ragione della necessità di consentire al Comitato Organizzatore di avviare il Campionato in tempi brevi e di predisporre tempestivamente il calendario ufficiale della competizione.",
      "Contestualmente al deposito della domanda di iscrizione, la squadra partecipante dovrà provvedere al versamento della quota di iscrizione al Campionato, che per l’edizione sportiva 2026/2027 è stabilita in € 200,00.",
      "In ogni caso, il pagamento della quota di iscrizione dovrà essere effettuato entro e non oltre il 25 settembre 2026.",
      "La copia della ricevuta/contabile del bonifico dovrà essere trasmessa nella medesima giornata in cui viene effettuato il pagamento ai seguenti indirizzi di posta elettronica:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "Nella causale del bonifico dovranno essere obbligatoriamente indicati:",
      "- la denominazione della società/associazione affiliata;",
      "- il/i Campionato/i ASI al quale/i la società intende partecipare.",
      "## ATTENZIONE – VALIDITA’ DEI VERSAMENTI",
      "Ai fini della regolare contabilizzazione del pagamento, il versamento si intenderà correttamente effettuato esclusivamente a condizione che la relativa contabile bancaria sia stata trasmessa agli indirizzi e-mail sopra indicati entro i termini stabiliti.",
      "Contestualmente, le squadre partecipanti dovranno aver regolarizzato la propria affiliazione all’Ente di Promozione Sportiva A.S.I., nel rispetto delle procedure, dei termini e dei costi stabiliti dall’Ente medesimo.",
      "## TESSERAMENTO DEI CALCIATORI",
      "Le procedure relative al tesseramento PER L’INTERA STAGIONE SPORTIVA dei calciatori (fino al 31/08/2027) saranno definite separatamente con l’A.S.I. entro il giorno lavorativo antecedente la prima gara del Campionato, nel rispetto dei costi, delle modalità e delle procedure stabilite dall’Ente di Promozione Sportiva, secondo quanto già previsto e applicato nelle precedenti edizioni. Il costo di ciascun tesseramento per l’attuale stagione sportiva è pari ad euro 15,00 sia per i calciatori che per dirigenti ed allenatori che partecipano ai campionati di calcio ASI.",
      "## LISTA DEI CALCIATORI",
      "All’atto dell’iscrizione al Campionato, ciascuna squadra dovrà depositare presso il Comitato Organizzatore la lista dei calciatori che intende utilizzare nel corso della competizione.",
      "La lista potrà contenere un numero massimo di 40 (quaranta) calciatori.",
      "Fermo restando quanto previsto dalle ulteriori disposizioni del presente Regolamento, qualora una squadra presenti inizialmente una lista composta da un numero di calciatori inferiore a 40, sarà consentito procedere all’integrazione della medesima lista fino al termine della seconda giornata di Campionato e più precisamente prima che inizi la terza.",
      "Decorso tale termine, la lista dei calciatori si intenderà definitivamente acquisita e non potrà essere ulteriormente integrata, salvo quanto eventualmente previsto da specifiche disposizioni del presente Regolamento o da eventuali deroghe espressamente autorizzate dal Comitato Organizzatore.",
      "Le finestre temporali previste dal presente Regolamento per il tesseramento e/o l’integrazione degli organici sono stabilite al fine di garantire la regolarità, l’equità e l’integrità sportiva della competizione.",
      "Pertanto, i calciatori eventualmente tesserati presso l’E.P.S. al di fuori delle suddette finestre temporali non potranno essere schierati in gara dalle rispettive squadre fino alla regolarizzazione della loro posizione e comunque nel rispetto delle disposizioni del presente Regolamento.",
      "L’utilizzo di un calciatore in violazione delle suddette disposizioni comporterà la considerazione della posizione del calciatore come irregolare, con conseguente applicazione delle sanzioni previste dal presente Regolamento e dalla normativa sportiva applicabile.",
      "Non sono ammesse deroghe di alcun genere alle disposizioni relative alle finestre di tesseramento e ai termini stabiliti dal presente Regolamento, salvo eventuali disposizioni inderogabili dell’Ente di Promozione Sportiva competente.",
      "## DIVIETO DI CAMBIO DI SQUADRA",
      "Non sono consentiti trasferimenti o cambi di squadra dei calciatori durante lo svolgimento del Campionato.",
      "In deroga a tale principio, esclusivamente durante le finestre di trasferimento espressamente individuate dal presente Regolamento, ciascuna squadra potrà tesserare un solo calciatore che risulti già tesserato e/o abbia precedentemente partecipato al Campionato con un’altra squadra iscritta alla medesima competizione.",
      "Il calciatore trasferito ai sensi della presente disposizione, una volta effettuato il cambio di squadra, non potrà essere successivamente trasferito o tesserato per un’ulteriore squadra partecipante al Campionato per tutta la durata della manifestazione.",
      "## PROCEDURA PER IL CAMBIO DI SQUADRA",
      "Il cambio di squadra dovrà essere oggetto di preventiva comunicazione scritta, da effettuarsi almeno due giorni lavorativi antecedenti la data prevista per il tesseramento o per l’utilizzo del calciatore, al Comitato Provinciale A.S.I., mediante invio agli indirizzi:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "La comunicazione dovrà essere altresì effettuata nel gruppo WhatsApp ufficiale del Campionato, al fine di garantire la massima trasparenza nei confronti delle squadre partecipanti.",
      "Il cambio di squadra sarà considerato valido esclusivamente a seguito della conferma espressa del Dirigente Responsabile della squadra di provenienza, attestante la cessazione della partecipazione del calciatore alla propria squadra e il nulla osta al trasferimento.",
      "In assenza della suddetta conferma, il trasferimento non potrà essere perfezionato né il calciatore potrà essere schierato dalla nuova squadra."
    ]
  },
  {
    "id": "art-4",
    "label": "Art. 4",
    "title": "Coppe ed eventi sportivi",
    "blocks": [
      "Durante e/o al termine del Campionato, le squadre partecipanti potranno essere ammesse alla partecipazione a ulteriori competizioni e manifestazioni organizzate sotto l’egida dell’A.S.I., comprese eventuali competizioni interregionali, se organizzate dal C.O. a titolo gratuito ovvero a pagamento.",
      "Tali manifestazioni potranno prevedere la partecipazione di squadre affiliate all’A.S.I. appartenenti ad altri Comitati Regionali e/o Provinciali e potranno svolgersi mediante gara unica ovvero, ove previsto dal relativo regolamento, mediante incontri di andata e ritorno.",
      "Le squadre che risulteranno vincitrici delle competizioni previste accederanno, secondo le modalità stabilite dall’Organizzazione e dagli Organi A.S.I. competenti, alle eventuali fasi successive finalizzate all’assegnazione della Supercoppa Italiana A.S.I. 2027/2028.",
      "## MODALITÀ DI SVOLGIMENTO E COSTI DELLE GARE",
      "Le gare della Coppa Italia A.S.I. – Comitato Provinciale di Roma saranno disputate in gara unica, salvo diversa disposizione del Comitato Organizzatore. Gli impianti sportivi presso i quali si svolgeranno gli incontri saranno individuati dal Comitato Organizzatore. I costi relativi all’affitto del campo di gioco e alle competenze arbitrali saranno sostenuti dalle due squadre partecipanti in misura pari al 50% ciascuna, salvo diversa disposizione preventivamente comunicata dal Comitato Organizzatore."
    ]
  },
  {
    "id": "art-5",
    "label": "Art. 5",
    "title": "Certificazioni mediche",
    "blocks": [
      "Ogni squadra, al momento della partecipazione dei propri calciatori alle gare, è tenuta a essere in possesso della documentazione attestante la certificazione medica di idoneità alla pratica dell’attività sportiva agonistica per ciascun atleta regolarmente tesserato.",
      "La società e/o il Dirigente Responsabile dovranno altresì essere in possesso di un documento di identità valido di ciascun calciatore, da esibire, ove richiesto, agli Organi competenti e/o al Comitato Organizzatore.",
      "È fatto assoluto divieto di schierare o consentire la partecipazione alla gara a calciatori privi della prescritta certificazione di idoneità sportiva in corso di validità. Tale documento dovrà essere in possesso del responsabile della società che si impegna a custodirli.",
      "La società partecipante e il relativo Dirigente Responsabile sono direttamente responsabili della verifica della validità e della regolarità della documentazione dei propri calciatori, nonché del rispetto delle disposizioni in materia di idoneità alla pratica sportiva.",
      "La partecipazione di un calciatore privo della prescritta idoneità sportiva, ovvero l’inosservanza degli obblighi documentali previsti dal presente articolo, comporterà l’adozione dei provvedimenti e delle eventuali sanzioni previste dal presente Regolamento, ferma restando ogni ulteriore responsabilità a carico dei soggetti cui sia imputabile la violazione.",
      "L’Organizzazione del Campionato e l’A.S.I. non assumono responsabilità per la mancata verifica, da parte della società partecipante e dei suoi rappresentanti, della sussistenza dei requisiti di idoneità e della regolarità della documentazione dei propri calciatori, fatto salvo quanto inderogabilmente previsto dalla normativa vigente.",
      "Altresì il C.O. non si assume la responsabilità per eventuali mancanze o danneggiamenti agli impianti sportivi inclusi gli spogliatoi. Lo stesso C.O. è manlevato dalla responsabilità di eventuali danni commessi dai partecipanti alla competizione a strutture e/o persone."
    ]
  },
  {
    "id": "art-6",
    "label": "Art. 6",
    "title": "Adempimenti pre-gara",
    "blocks": [
      "## PRESENTAZIONE DELLA DISTINTA DI GARA",
      "Ogni squadra è tenuta a presentare al Direttore di Gara, almeno 20 minuti prima dell’orario ufficiale di inizio dell’incontro, l’elenco nominativo dei partecipanti alla gara, redatto sull’apposito modello ufficiale fornito dal Comitato Organizzatore.",
      "La distinta di gara dovrà essere presentata in triplice copia e potrà contenere un numero massimo di 20 calciatori, scelti esclusivamente tra i calciatori regolarmente inseriti nella lista dei 40 depositata presso il Comitato Organizzatore.",
      "Le tre copie della distinta dovranno essere sottoscritte dal Dirigente Responsabile della squadra, purché regolarmente indicato nella distinta stessa e presente alla gara. In sua assenza, la distinta potrà essere sottoscritta dal Capitano della squadra, che ne assumerà la relativa responsabilità per quanto concerne la corretta compilazione e sottoscrizione.",
      "La firma dovrà essere apposta alla presenza del Direttore di Gara.",
      "## DATI OBBLIGATORI DELLA DISTINTA",
      "La distinta dei partecipanti alla gara dovrà essere compilata esclusivamente utilizzando il modello ufficiale predisposto dal Comitato Organizzatore e dovrà contenere, obbligatoriamente, almeno le seguenti informazioni:",
      "- nominativo dei calciatori e dei dirigenti presenti;",
      "- indicazione del Capitano;",
      "- indicazione del Vice Capitano;",
      "- numero di tessera A.S.I. di ciascun calciatore e dirigente;",
      "- numero del documento di identità di ciascun calciatore e dirigente, qualora non venga esibita la tessera A.S.I. originale;",
      "- ogni ulteriore informazione richiesta dal modello ufficiale della distinta.",
      "La responsabilità della corretta e completa compilazione della distinta è attribuita al Dirigente Responsabile della squadra ovvero, in sua assenza, al Capitano che provveda alla sottoscrizione della stessa.",
      "## RICONOSCIMENTO DEI PARTECIPANTI",
      "Il Direttore di Gara procederà al riconoscimento dei calciatori e dei dirigenti inseriti nella distinta di gara attraverso la tessera A.S.I. originale ovvero, qualora questa non sia disponibile, mediante un documento di identità valido e riconosciuto dallo Stato italiano, in originale.",
      "In assenza del documento di identità originale, qualora non sia disponibile la tessera A.S.I. originale, il soggetto interessato non potrà prendere parte alla gara né essere inserito tra i partecipanti effettivi all’incontro.",
      "Non saranno pertanto ritenute sufficienti, ai fini del riconoscimento, copie, fotografie o riproduzioni non conformi ai documenti richiesti, salvo diversa disposizione espressamente prevista dall’A.S.I. o dal Comitato Organizzatore.",
      "## DOCUMENTAZIONE PER IL TESSERAMENTO – ADEMPIMENTO TASSATIVO",
      "Tutti i Dirigenti Responsabili delle squadre dovranno trasmettere, entro il 30 settembre, all’indirizzo di posta elettronica: info@asiroma.org la documentazione necessaria per il tesseramento dei propri calciatori e dirigenti, costituita da:",
      "- fototessera recente, con sfondo bianco, di ciascun soggetto da tesserare;",
      "- copia/scansione leggibile del documento di identità in corso di validità di ciascun soggetto da tesserare;",
      "- ogni ulteriore documentazione eventualmente richiesta dall’A.S.I. – Comitato Provinciale di Roma.",
      "La documentazione dovrà essere completa e correttamente leggibile, al fine di consentire il regolare perfezionamento delle procedure di tesseramento.",
      "## CALCIATORI DI NUOVO TESSERAMENTO",
      "Nelle more del perfezionamento della procedura di tesseramento e fino alla consegna del tesserino A.S.I. plastificato, i nuovi calciatori regolarmente iscritti e tesserati, ove autorizzati secondo le procedure dell’A.S.I., potranno essere ammessi alla gara mediante l’esibizione del tesserino cartaceo ricevuto tramite e-mail, unitamente al documento di identità originale in corso di validità.",
      "Tale possibilità è da intendersi esclusivamente come procedura transitoria, nelle more del ritiro del tesserino plastificato presso il Comitato Provinciale A.S.I. di Roma e comunque entro quattordici giorni dalla data del tesseramento.",
      "Il nuovo calciatore dovrà provvedere al ritiro del tesserino plastificato entro il termine stabilito dal Comitato Organizzatore e, comunque, entro la prima giornata utile successiva al perfezionamento del tesseramento, secondo le procedure comunicate dall’A.S.I. Decorso tale termine, l’ammissione alla gara sarà subordinata alla regolare disponibilità della documentazione richiesta.",
      "## DIRIGENTI AMMESSI NEL RECINTO DI GIOCO E AMMESSI AL SUO INTERNO",
      "Sono autorizzati a essere inseriti nella distinta di gara e, conseguentemente, ad accedere e permanere nel recinto di gioco durante lo svolgimento dell’incontro esclusivamente i seguenti soggetti:",
      "Allenatore; Vice Allenatore; Dirigente Responsabile della squadra, che dovrà essere il soggetto incaricato di sottoscrivere la distinta di gara, salvo quanto previsto in caso di sua assenza; Medico sociale, ove presente e regolarmente autorizzato.",
      "Nessun altro dirigente, collaboratore, accompagnatore o soggetto non espressamente indicato nella distinta e autorizzato secondo le disposizioni del presente Regolamento potrà accedere al recinto di gioco durante la gara. Non possono entrare nel recinto di giuoco in modo assoluto, animali e figli di tesserati non inseriti in distinta di gara.",
      "## TESSERAMENTO DEI DIRIGENTI",
      "Tutti i Dirigenti, inclusi Medico e personale sanitario, dovranno essere regolarmente tesserati per la società di appartenenza e risultare inseriti nella documentazione prevista dal presente Regolamento.",
      "Il Medico eventualmente presente dovrà essere in possesso di idonea documentazione attestante la propria qualifica professionale, da esibire, ove richiesta, al Direttore di Gara o agli Organi competenti. Questi dovranno essere specificati nel loro speciale RUOLO al momento della loro iscrizione attraverso comunicazione a torneiasicalciolazio@gmail.com .",
      "## FUORIQUOTA E TITOLARI",
      "I calciatori “fuoriquota”, dovranno essere espressamente identificati nella distinta di gara mediante l’apposizione dell’acronimo “FQ” accanto al relativo nominativo.",
      "Nella distinta di gara dovranno inoltre essere indicati i calciatori titolari iniziali, contrassegnando il relativo nominativo con la lettera “T”, da apporre prima del numero di maglia.",
      "La corretta indicazione dei calciatori fuoriquota e dei titolari nella distinta di gara costituisce obbligo della squadra e del Dirigente Responsabile che provvede alla sottoscrizione della distinta.",
      "## POSIZIONE IRREGOLARE DEI CALCIATORI",
      "È considerato in posizione irregolare il calciatore che, a titolo esemplificativo e non esaustivo:",
      "- non possieda i requisiti anagrafici previsti dal Campionato;",
      "- non sia regolarmente iscritto al Campionato;",
      "- non sia regolarmente tesserato per la società con la quale viene schierato;",
      "- sia stato tesserato al di fuori delle finestre temporali previste dal presente Regolamento;",
      "- non sia inserito nella lista dei calciatori depositata presso il Comitato Organizzatore;",
      "- non sia inserito nella distinta di gara;",
      "- non disponga della documentazione richiesta per la partecipazione alla gara;",
      "- sia comunque privo dei requisiti necessari per poter essere regolarmente schierato.",
      "Qualora una squadra schieri o faccia partecipare a una gara un calciatore in posizione irregolare, alla stessa sarà inflitta la sconfitta a tavolino con il risultato di 0-3, oltre alla penalizzazione di un punto nella classifica generale.",
      "La squadra responsabile sarà inoltre tenuta al pagamento della relativa multa di euro 150,00 che andrà devoluta a fine stagione a titolo benefico, anche qualora rivesta il ruolo di squadra ospite.",
      "In caso di seconda infrazione, il Comitato Organizzatore e/o gli Organi competenti potranno disporre l’esclusione della squadra dal Campionato, fatta salva l’applicazione delle ulteriori sanzioni previste dal presente Regolamento e l’eventuale pagamento della penale stabilita dal Comitato Organizzatore.",
      "## RAPPRESENTANTE E VICE RAPPRESENTANTE DI SQUADRA",
      "Ogni squadra dovrà nominare un Rappresentante di squadra e un Vice Rappresentante, che costituiranno i referenti ufficiali della rispettiva rappresentativa nei rapporti con il Comitato Organizzatore. I suddetti soggetti saranno altresì chiamati a collaborare affinché i calciatori, i dirigenti e gli altri tesserati della propria squadra mantengano un comportamento conforme al presente Regolamento e ai principi di correttezza, lealtà e disciplina sportiva. Sul terreno di giuoco e durante una gara, anche il capitano è responsabile dei suoi tesserati.",
      "Resta ferma la responsabilità individuale dei singoli soggetti per le condotte personalmente poste in essere.",
      "## COMUNICAZIONE DELL'ORGANICO",
      "Ciascuna squadra dovrà trasmettere al Comitato Organizzatore la lista definitiva dei calciatori e dei Rappresentanti di squadra entro e non oltre il 30 settembre 2026, secondo le modalità previste dal presente Regolamento.",
      "Eventuali successive variazioni potranno essere effettuate esclusivamente nei casi e nei termini espressamente consentiti dal presente Regolamento.",
      "## AFFITTO DEGLI IMPIANTI SPORTIVI",
      "I costi relativi all’affitto degli impianti sportivi individuati dalle squadre partecipanti per la disputa delle gare casalinghe saranno integralmente a carico della squadra ospitante, salvo diversa disposizione concordata o stabilita dal Comitato Organizzatore.",
      "## COPERTURA ASSICURATIVA E TESSERAMENTO A.S.I.",
      "All’atto dell’iscrizione al Campionato, le squadre accettano l’obbligo di provvedere, a propria cura e spese, al regolare tesseramento A.S.I. dei propri calciatori, tecnici, dirigenti e collaboratori, comprensivo della relativa copertura assicurativa prevista dall’Ente.",
      "Per la stagione sportiva 2026/2027, il costo del tesseramento, valido fino al 31/08/2027, è indicato in € 15,00 per ciascun soggetto, salvo eventuali variazioni stabilite dall’A.S.I. I relativi versamenti dovranno essere effettuati secondo le modalità indicate dal Comitato Provinciale A.S.I. di Roma, utilizzando le coordinate bancarie riportate nel presente Regolamento.",
      "La copia della relativa ricevuta di pagamento dovrà essere trasmessa entro e non oltre il 30 settembre 2026 ai seguenti indirizzi di posta elettronica: info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it americo.scatena@gmail.com - torneiasicalciolazio@gmail.com La società partecipante e il relativo Dirigente Responsabile sono tenuti a verificare che tutti i soggetti destinati a partecipare alle attività sportive siano regolarmente tesserati e in possesso dei requisiti previsti dalla normativa vigente.",
      "Per quanto concerne la responsabilità dell’Organizzazione e la copertura assicurativa, si applicano le disposizioni di legge, le condizioni della polizza assicurativa A.S.I. e quanto previsto dal presente Regolamento. La sottoscrizione del presente Regolamento non comporta rinuncia a diritti o responsabilità inderogabili previsti dalla normativa vigente.",
      "## OBBLIGHI DELLA SQUADRA OSPITANTE",
      "La squadra ospitante è tenuta, in occasione delle gare disputate sul proprio campo, a garantire la disponibilità di una idonea Borsa di Emergenza Medica, adeguatamente fornita per la gestione delle eventuali necessità di primo intervento, secondo quanto previsto dalla normativa vigente e dalle disposizioni dell’Organizzazione. La squadra ospitante dovrà altresì assicurarsi che gli spogliatoi destinati alle squadre e alla terna arbitrale siano mantenuti in condizioni decorose, igienicamente idonee e fruibili, nonché dotati di acqua calda per le docce. L’inosservanza di tali obblighi comporterà, salvo ulteriori provvedimenti, un richiamo formale alla società ospitante e potrà prevedere, in caso di recidiva, una sanzione pecuniaria pari al 50% della quota prevista per l’affitto dell’impianto sportivo. La somma dovrà essere versata sul conto corrente intestato all’A.S.I. – Comitato Provinciale di Roma, secondo le modalità comunicate dal Comitato Organizzatore.",
      "## INCOMPATIBILITÀ CON IL TESSERAMENTO F.I.G.C.",
      "Non possono partecipare al Campionato i calciatori che risultino tesserati, nella stagione sportiva in corso, per società affiliate alla F.I.G.C., anche qualora siano successivamente svincolati nel corso della medesima stagione sportiva. Il divieto si applica per tutta la durata della stagione sportiva, salvo eventuali diverse disposizioni espressamente previste dalla normativa A.S.I. o dagli Organi competenti. Tale divieto non è previsto per allenatori e dirigenti.",
      "## PARTECIPAZIONE A PIÙ COMPETIZIONI A.S.I.",
      "Fermo restando quanto previsto dal presente Regolamento in materia di trasferimenti e cambi di squadra, un calciatore regolarmente tesserato con una società partecipante a una competizione A.S.I. potrà, nella medesima stagione sportiva, partecipare anche a un’altra competizione A.S.I. con una diversa società affiliata, purché:",
      "- la seconda società partecipi a una competizione diversa da quella nella quale il calciatore è già tesserato;",
      "- il calciatore risulti regolarmente tesserato anche per la seconda società;",
      "- siano rispettate tutte le disposizioni A.S.I. relative al tesseramento e alla partecipazione alle competizioni;",
      "- non venga violato il divieto di trasferimento previsto dal presente Regolamento nell’ambito della medesima competizione.",
      "A titolo esemplificativo, il calciatore Mario Rossi, regolarmente tesserato e partecipante con la squadra Roma al Campionato Over 35, potrà partecipare, nella medesima stagione sportiva, anche al Campionato Over 45 con la squadra Lazio, purché risulti regolarmente tesserato anche per quest’ultima società e siano rispettate tutte le condizioni previste dal presente Regolamento e dalla normativa A.S.I.",
      "## SANZIONI PER POSIZIONE IRREGOLARE",
      "Il mancato rispetto delle disposizioni di cui al presente articolo, nonché l’utilizzo di calciatori in posizione irregolare, comporterà, per ciascuna gara nella quale il calciatore sia stato schierato o abbia preso parte all’incontro, la sconfitta a tavolino della squadra responsabile con il risultato di 0-3, oltre alla penalizzazione di un punto nella classifica generale. Restano ferme l’applicazione delle ulteriori sanzioni eventualmente previste dal presente Regolamento e le competenze degli Organi di Giustizia Sportiva dell’A.S.I."
    ]
  },
  {
    "id": "art-7",
    "label": "Art. 7",
    "title": "Formula del campionato",
    "blocks": [
      "## CALENDARIO DELLA COMPETIZIONE",
      "Le squadre partecipanti disputeranno le gare secondo il calendario ufficiale predisposto e pubblicato dal Comitato Organizzatore, che stabilirà date, orari, impianti e ordine degli incontri.",
      "Il Campionato avrà inizio, indicativamente, entro il mese di ottobre 2026 e si svolgerà, di norma, con cadenza quindicinale, secondo il calendario predisposto dal Comitato Organizzatore.",
      "La cadenza delle gare potrà subire variazioni in relazione alle esigenze organizzative, alla disponibilità degli impianti sportivi, alle festività, alle condizioni meteorologiche o ad altre comprovate esigenze connesse allo svolgimento della manifestazione. Per la formula del campionato si fa riferimento all’allegato n.1 della stagione in corso per ciascun campionato organizzato da A.S.I.",
      "## ORARIO DELLE GARE E PUNTUALITÀ",
      "L’orario di inizio delle gare sarà indicativamente compreso tra le ore 20:30 e le ore 21:30, in funzione della disponibilità degli impianti sportivi e delle esigenze organizzative delle singole squadre.",
      "Le società partecipanti sono tenute a garantire la massima puntualità, presentandosi presso l’impianto sportivo con congruo anticipo rispetto all’orario ufficiale di gara, al fine di consentire le operazioni di riconoscimento, compilazione e sottoscrizione delle distinte e ogni altro adempimento preliminare.",
      "È previsto un tempo di attesa massimo di 15 minuti rispetto all’orario ufficiale di inizio della gara.",
      "Decorso tale termine, qualora una squadra non sia in grado di iniziare l’incontro con almeno 9 (nove) calciatori, sarà dichiarata rinunciataria e subirà la sconfitta a tavolino, secondo le disposizioni sanzionatorie previste dal presente Regolamento.",
      "Qualora, invece, la squadra sia presente con almeno 9 calciatori entro il termine di attesa, la gara dovrà avere regolare inizio, fermo restando quanto previsto dalle altre disposizioni del presente Regolamento.",
      "## INDICAZIONE DELLE GIORNATE DI PREFERENZA",
      "All’atto dell’iscrizione, ogni squadra dovrà indicare obbligatoriamente 2 (due) giorni di preferenza settimanale, dal lunedì al venerdì, nei quali rendersi disponibile per la disputa delle proprie gare interne.",
      "Tale indicazione è da considerarsi obbligatoria e tassativa, ma non costituisce un vincolo per il Comitato Organizzatore.",
      "Le preferenze espresse saranno tenute in considerazione compatibilmente con le esigenze generali della competizione, con la disponibilità degli impianti e con la necessità di predisporre un calendario equilibrato e funzionale per tutte le squadre partecipanti.",
      "## CAMPO DI GIOCO",
      "All’atto dell’iscrizione, ciascuna squadra dovrà indicare il proprio campo di gioco, presso il quale saranno disputate le gare nelle quali risulterà formalmente squadra ospitante.",
      "Le spese relative all’affitto dell’impianto sportivo saranno integralmente a carico della squadra ospitante, salvo diversa disposizione del Comitato Organizzatore.",
      "La società ospitante è inoltre tenuta a garantire la disponibilità di uno spogliatoio idoneo e adeguato per la terna arbitrale, nel rispetto delle disposizioni organizzative e di sicurezza previste per la manifestazione.",
      "## IMMODIFICABILITÀ DEL CALENDARIO",
      "Il calendario ufficiale, una volta pubblicato dal Comitato Organizzatore, deve intendersi definitivo e, come regola generale, non modificabile.",
      "Le squadre partecipanti sono pertanto tenute a organizzare la propria attività sportiva nel rispetto delle date e degli orari ufficialmente comunicati.",
      "## RICHIESTA DI POSTICIPO",
      "In via eccezionale, qualora ricorrano fondati e comprovati motivi, le due squadre interessate potranno concordare il posticipo della gara entro la settimana immediatamente successiva rispetto alla data originariamente prevista.",
      "La richiesta dovrà essere presentata al Comitato Organizzatore con almeno 14 giorni di anticipo rispetto alla data originariamente fissata per l’incontro e dovrà contenere l’indicazione della nuova data proposta, previamente concordata tra le società.",
      "La richiesta non determina automaticamente il rinvio della gara, che potrà essere disposto esclusivamente previa autorizzazione del Comitato Organizzatore, tenuto conto delle esigenze generali della competizione e della disponibilità degli impianti e della terna arbitrale.",
      "In caso di autorizzazione, la società richiedente o, qualora diversamente concordato, le società interessate saranno tenute al pagamento di una penale di € 50,00 da versare all’A.S.I. – Comitato Provinciale di Roma, secondo le modalità indicate dal Comitato Organizzatore.",
      "In assenza di preventiva autorizzazione, la gara dovrà essere disputata nella data e nell’orario originariamente stabiliti dal calendario ufficiale.",
      "## SPOSTAMENTO DELLE GARE NELLE ULTIME GIORNATE",
      "In deroga alla disciplina generale prevista per gli spostamenti delle gare, nelle ultime tre giornate di Campionato sarà eccezionalmente consentito richiedere lo spostamento di un incontro, esclusivamente previo accordo tra le due squadre interessate.",
      "La richiesta e la gara dovrà essere effettuata entro e non oltre il venerdì della medesima settimana nella quale è programmata la gara secondo il calendario ufficiale.",
      "L’eventuale accordo raggiunto tra le società dovrà essere formalmente confermato da entrambe le squadre nella chat ufficiale WhatsApp del Campionato.",
      "Lo spostamento non potrà in alcun caso ritenersi automaticamente autorizzato per effetto del solo accordo tra le società, essendo necessaria la preventiva approvazione del Comitato Provinciale A.S.I. di Roma.",
      "## CARATTERE ECCEZIONALE DELLO SPOSTAMENTO",
      "Lo spostamento della gara previsto al precedente comma deve intendersi quale misura di carattere assolutamente eccezionale.",
      "Il Comitato Provinciale A.S.I. di Roma conserva pertanto la piena facoltà di non autorizzare lo spostamento, anche in presenza dell’accordo tra le due squadre, qualora lo stesso risulti incompatibile con le esigenze organizzative, sportive o regolamentari della competizione.",
      "In assenza di espressa autorizzazione, la gara dovrà essere disputata nella data e nell’orario stabiliti dal calendario ufficiale.",
      "## DURATA DELLE GARE",
      "Le gare del Campionato si svolgeranno in due tempi di 35 (trentacinque) minuti ciascuno, con un intervallo tra i due tempi della durata massima di 15 (quindici) minuti.",
      "Gli incontri saranno diretti, di norma, da una terna arbitrale messa a disposizione dall’A.S.I., composta da: un Direttore di Gara; due Assistenti Arbitrali.",
      "Qualora, per motivazioni organizzative o per altre cause non imputabili alle squadre, sia disponibile un solo Direttore di Gara, l’incontro potrà essere disputato con il solo arbitro, secondo le disposizioni dell’A.S.I. In tale eventualità, la quota arbitrale complessiva sarà pari a € 90,00.",
      "## COMPENSO DELLA TERNA ARBITRALE",
      "Il costo della terna arbitrale è stabilito in € 140,00 per ciascuna gara, da suddividere in parti uguali tra le due squadre partecipanti.",
      "Ciascuna società dovrà pertanto corrispondere la somma di € 70,00, da consegnare al momento della presentazione delle distinte dei partecipanti alla gara, salvo diverse modalità di pagamento eventualmente comunicate dal Comitato Organizzatore.",
      "## TEMPO DI ATTESA E INIZIO DELLA GARA",
      "Il tempo massimo di attesa rispetto all’orario ufficiale di inizio della gara è fissato in 15 (quindici) minuti.",
      "Decorso tale termine, la gara dovrà obbligatoriamente avere inizio con i calciatori regolarmente presenti e in possesso dei requisiti necessari per prendere parte all’incontro, purché sia rispettato il numero minimo di calciatori previsto dal presente Regolamento.",
      "Qualora una squadra, decorso il termine di attesa, non sia in grado di schierare il numero minimo di calciatori previsto per l’inizio della gara, sarà dichiarata rinunciataria e subirà:",
      "- la sconfitta a tavolino con il risultato di 0-3;",
      "- la penalizzazione di 1 (un) punto nella classifica generale;",
      "- una sanzione pecuniaria pari a € 140,00.",
      "La sanzione pecuniaria dovrà essere corrisposta mediante bonifico bancario in favore dell’A.S.I. – Comitato Provinciale di Roma entro e non oltre la gara successiva in calendario della squadra sanzionata.",
      "Il mancato pagamento della sanzione entro il termine stabilito comporterà, previa comunicazione del Comitato Organizzatore, la sospensione della squadra dalla competizione e l’eventuale esclusione dal Campionato, secondo le disposizioni degli Organi competenti.",
      "Resta fermo quanto previsto dal presente Regolamento in ordine al numero minimo di calciatori necessario per l’inizio e per la prosecuzione della gara.",
      "## CALCIATORE SOPRAGGIUNTO A GARA INIZIATA",
      "Qualora un calciatore risulti regolarmente inserito nella distinta di gara, ma non sia presente al momento delle operazioni di riconoscimento pre-gara e raggiunga l’impianto sportivo successivamente all’inizio dell’incontro, egli potrà prendere parte alla gara esclusivamente dopo aver effettuato il necessario riconoscimento da parte del Direttore di Gara.",
      "Il calciatore dovrà pertanto presentarsi al Direttore di Gara ed esibire la documentazione richiesta per il riconoscimento, secondo quanto previsto dal presente Regolamento.",
      "È fatto espresso divieto al calciatore di accedere al recinto di gioco e di prendere parte all’incontro prima del completamento della procedura di riconoscimento.",
      "Una volta effettuato positivamente il riconoscimento, il calciatore potrà accedere al terreno di gioco secondo le modalità previste dalle Regole del Gioco e previa autorizzazione del Direttore di Gara.",
      "## TIME-OUT",
      "Ciascuna squadra avrà diritto a usufruire di un time-out per ciascun tempo di gioco, della durata massima di 60 (sessanta) secondi.",
      "Il time-out dovrà essere richiesto esclusivamente dall’Allenatore della squadra, dalla propria area tecnica, e potrà essere concesso dal Direttore di Gara esclusivamente quando la squadra richiedente si trovi in possesso del pallone.",
      "La richiesta di time-out dovrà essere manifestata in modo chiaro al Direttore di Gara, che ne autorizzerà l’effettuazione nel rispetto delle condizioni previste dal presente articolo.",
      "Il time-out non potrà essere richiesto o concesso qualora la squadra richiedente non sia in possesso del pallone.",
      "## COOLING BREAK",
      "In presenza di condizioni climatiche particolarmente gravose o di altre circostanze eccezionali, il Direttore di Gara, sentiti gli eventuali soggetti competenti, potrà disporre un ulteriore cooling break della durata massima di 1 (un) minuto.",
      "La decisione in ordine alla concessione del cooling break è rimessa alla valutazione del Direttore di Gara, tenuto conto delle condizioni concrete riscontrate durante l’incontro.",
      "## ATTRIBUZIONE DEI PUNTI",
      "Al termine dei 70 minuti regolamentari di gioco, i punti saranno assegnati secondo il seguente criterio:",
      "- 3 punti alla squadra vincitrice;",
      "- 0 punti alla squadra sconfitta;",
      "- 1 punto a ciascuna squadra in caso di pareggio.",
      "L’assegnazione dei punti sarà effettuata sulla base del risultato omologato dagli Organi competenti.",
      "## PALLONI DI GARA",
      "La squadra ospitante è tenuta a mettere a disposizione, per ciascuna gara disputata sul proprio impianto, almeno 4 (quattro) palloni regolamentari e idonei allo svolgimento dell’incontro.",
      "La squadra ospitata è tenuta, a propria volta, a presentarsi presso l’impianto sportivo con almeno 2 (due) palloni regolamentari e idonei, da utilizzare in caso di necessità durante lo svolgimento della gara.",
      "L’eventuale mancata disponibilità del numero minimo di palloni previsto dal presente articolo, qualora espressamente rilevata e riportata dal Direttore di Gara nel referto ufficiale, comporterà l’applicazione di una sanzione pecuniaria pari a € 30,00 a carico della società inadempiente.",
      "## EQUIPAGGIAMENTO E COLORI DELLE DIVISE",
      "Per quanto concerne l’equipaggiamento dei calciatori, si applicano le disposizioni previste dalle Regole del Gioco del Calcio e dalla normativa sportiva vigente, salvo quanto diversamente stabilito dal presente Regolamento.",
      "All’atto dell’iscrizione al Campionato, ciascuna società dovrà indicare, nell’apposita scheda anagrafica della società, i colori di almeno 2 (due) divise ufficiali di gara, sufficientemente distinguibili tra loro.",
      "La squadra ospitante ha l’obbligo di garantire che la propria divisa di gara sia chiaramente distinguibile da quella della squadra ospitata.",
      "Qualora i colori delle divise risultino tra loro confondibili, sarà la squadra ospitante a dover provvedere alla sostituzione della propria divisa con una seconda divisa o con un equipaggiamento alternativo idoneo a garantire la corretta distinzione cromatica.",
      "È comunque raccomandata una preventiva collaborazione tra le società, anche mediante comunicazioni dirette tra i rispettivi Dirigenti Responsabili, al fine di evitare situazioni di possibile confusione cromatica prima dell’inizio dell’incontro.",
      "## OBBLIGO DI PORTARE A TERMINE LA COMPETIZIONE",
      "Le squadre regolarmente iscritte al Campionato assumono l’obbligo di partecipare e di portare regolarmente a termine tutte le gare e l’intera manifestazione, salvo cause di forza maggiore o altre circostanze riconosciute dagli Organi competenti.",
      "La rinuncia ingiustificata alla disputa di una singola gara comporterà, a carico della squadra rinunciataria:",
      "- la sconfitta a tavolino con il risultato di 0-3;",
      "- la penalizzazione di 1 (un) punto nella classifica generale;",
      "- l’applicazione di una sanzione pecuniaria pari a € 140,00.",
      "La sanzione pecuniaria dovrà essere corrisposta secondo le modalità e nei termini stabiliti dal Comitato Organizzatore.",
      "Restano ferme le ulteriori conseguenze disciplinari previste dal presente Regolamento in caso di reiterazione delle rinunce o di abbandono della competizione.",
      "## RINUNCIA AL CAMPIONATO",
      "In caso di rinuncia, abbandono o ritiro dal Campionato successivamente all’iscrizione, la squadra rinunciataria sarà tenuta al pagamento di una penale pari a € 200,00, oltre all’integrale pagamento di tutte le eventuali sanzioni pecuniarie e multe maturate fino alla data della rinuncia.",
      "Le somme dovute dovranno essere corrisposte entro e non oltre 7 (sette) giorni dalla comunicazione della rinuncia ovvero, in mancanza di comunicazione formale, dalla data in cui il Comitato Organizzatore abbia accertato l’effettivo ritiro della squadra dalla manifestazione.",
      "Il Dirigente Responsabile della squadra è tenuto a garantire, per quanto di propria competenza, l’adempimento delle obbligazioni economiche derivanti dalla partecipazione della società alla manifestazione, secondo quanto previsto dal presente Regolamento e dalla normativa applicabile.",
      "In caso di mancato pagamento entro il termine stabilito, fermo restando il permanere delle obbligazioni economiche maturate, alla squadra inadempiente e ai relativi tesserati potrà essere preclusa la partecipazione alle due successive edizioni del Campionato e, nei casi previsti dagli Organi competenti, anche ad altre manifestazioni organizzate sotto l’egida A.S.I.",
      "## RINUNCIA A UNA SINGOLA GARA",
      "In caso di rinuncia alla disputa di una singola gara, anche qualora la rinuncia venga comunicata con un preavviso sufficiente a consentire al Comitato Organizzatore di adottare le necessarie misure organizzative, la squadra rinunciataria sarà tenuta al pagamento di una penale di € 50,00 per ciascuna gara non disputata. La penale dovrà essere corrisposta entro e non oltre la gara immediatamente successiva alla rinuncia.",
      "Il mancato pagamento della penale entro il termine previsto comporterà l’applicazione delle ulteriori conseguenze previste dal presente Regolamento, fatta salva la possibilità per il Comitato Organizzatore di deferire la posizione agli Organi competenti.",
      "Qualora una squadra rinunci alla disputa di 3 (tre) gare nel corso della medesima competizione, sarà disposta l’esclusione dalla competizione, fatta salva l’obbligazione di corrispondere:",
      "- le penali relative alle singole gare alle quali ha rinunciato;",
      "- la penale di € 200,00 prevista per il ritiro dal Campionato;",
      "- ogni ulteriore sanzione pecuniaria eventualmente maturata.",
      "## MODALITÀ DI PAGAMENTO",
      "Le somme dovute a titolo di penale dovranno essere versate sul conto corrente dell’A.S.I. – Comitato Provinciale di Roma, secondo le coordinate bancarie riportate nel presente Regolamento.",
      "La relativa ricevuta di pagamento dovrà essere trasmessa tempestivamente ai seguenti indirizzi di posta elettronica:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "## OBBLIGO DI LEALTÀ E REGOLARE PARTECIPAZIONE",
      "Con l’iscrizione al Campionato, tutte le squadre partecipanti si impegnano a disputare le gare con la massima correttezza, lealtà e impegno sportivo, mettendo in campo, per quanto ragionevolmente possibile, la propria migliore formazione disponibile.",
      "Le squadre si impegnano altresì a non porre in essere condotte finalizzate ad alterare, condizionare o falsare il regolare svolgimento della competizione, nel rispetto dei principi di lealtà, correttezza e probità sportiva.",
      "## CRITERI DI CLASSIFICA IN CASO DI PARITÀ",
      "In caso di parità di punti in classifica tra due o più squadre, ai fini della determinazione della posizione in graduatoria e, ove necessario, dell’individuazione della squadra vincitrice del Campionato, si procederà applicando nell’ordine i seguenti criteri:",
      "- Classifica avulsa tra le squadre interessate;",
      "- Punti conseguiti negli scontri diretti tra le squadre interessate;",
      "- Migliore differenza reti, calcolata sulla totalità delle gare disputate;",
      "- Minor numero di reti subite nell’intero Campionato;",
      "- Maggior numero di reti segnate nell’intero Campionato;",
      "- Maggior numero di cartellini verdi A.S.I. assegnati ai calciatori della squadra;",
      "- Migliore posizione nella classifica disciplinare, determinata sulla base delle sanzioni disciplinari complessivamente ricevute;",
      "- Sorteggio, effettuato dal Comitato Organizzatore secondo modalità dallo stesso stabilite.",
      "Qualora uno dei criteri sopra indicati consenta di determinare la posizione di una o più squadre, il criterio successivo verrà applicato esclusivamente alle squadre per le quali permanga una situazione di parità.",
      "Le decisioni relative all’applicazione dei criteri di cui al presente articolo e alla conseguente formazione della classifica ufficiale sono di competenza del Comitato Organizzatore, nel rispetto delle disposizioni del presente Regolamento."
    ]
  },
  {
    "id": "art-8",
    "label": "Art. 8",
    "title": "Trofei",
    "blocks": [
      "Al termine della manifestazione, a ciascuna squadra partecipante sarà consegnato un trofeo di partecipazione, quale riconoscimento per la partecipazione al Campionato.",
      "## PREMIO FAIR PLAY",
      "Sarà assegnato il Premio Fair Play alla squadra che avrà conseguito il miglior risultato nella speciale graduatoria disciplinare predisposta dal Comitato Organizzatore.",
      "Ai fini della determinazione della graduatoria, sarà attribuita particolare rilevanza al maggior numero di Cartellini Verdi A.S.I. ricevuti dai propri calciatori nel corso della competizione. In caso di parità tra due o più squadre, il Premio sarà assegnato alla squadra che, nel corso dell’intero Campionato, avrà ricevuto il minor numero complessivo di cartellini rossi e cartellini gialli.",
      "## PREMI INDIVIDUALI",
      "Al termine del Campionato saranno inoltre assegnati i seguenti riconoscimenti individuali:",
      "- Premio al Miglior Realizzatore, assegnato al calciatore che avrà realizzato il maggior numero di reti;",
      "- Premio al Miglior Portiere;",
      "- Pallone d’Oro, assegnato al calciatore individuato sulla base del sistema di votazione previsto dal presente articolo.",
      "In caso di parità tra due o più calciatori ai fini dell’assegnazione di uno dei suddetti riconoscimenti, il premio sarà attribuito al calciatore appartenente alla squadra che avrà ottenuto il migliore piazzamento nella classifica finale del Campionato.",
      "## SISTEMA DI VOTAZIONE DELLA TERNA ARBITRALE",
      "Ai fini dell’assegnazione dei riconoscimenti individuali, la terna arbitrale procederà, ove previsto, alla votazione dei calciatori ritenuti meritevoli per la prestazione fornita durante la gara. Per il riconoscimento relativo ai portieri, saranno votati almeno due portieri, con attribuzione dei seguenti punteggi:",
      "- 3 punti al portiere ritenuto migliore della gara;",
      "- 1 punto all’altro portiere o, qualora siano presenti più portieri aventi diritto alla votazione, agli altri portieri individuati secondo le modalità stabilite dal Comitato Organizzatore.",
      "Per il riconoscimento relativo ai calciatori di movimento, saranno individuati due calciatori, con attribuzione dei seguenti punteggi:",
      "- 3 punti al calciatore ritenuto migliore della gara;",
      "- 1 punto a un calciatore appartenente alla squadra avversaria.",
      "I voti saranno raccolti e contabilizzati dal Comitato Organizzatore ai fini della formazione delle graduatorie individuali.",
      "Il sistema di votazione ha esclusivamente finalità di individuazione dei premi previsti dal presente Regolamento e non incide in alcun modo sull’esito sportivo della gara né sulle valutazioni e decisioni di competenza del Direttore di Gara."
    ]
  },
  {
    "id": "art-9",
    "label": "Art. 9",
    "title": "Distinta gara e sostituzioni",
    "blocks": [
      "Prima di ogni incontro, i Dirigenti di ciascuna squadra concorderanno sulla divisa da indossare e presenteranno all’arbitro designato la “DISTINTA DI GARA IN TRIPLICE COPIA” e relativi documenti di identità in originale per il riconoscimento ( possibilmente già in ordine di chiamata per l’appello).",
      "La lista gara dovrà essere redatta secondo il format fornito da ASI. Non sono ammesse liste gara valutate dal DG come illeggibili, o presentanti modifiche non approvate anche dal Direttore di Gara, o compilate parzialmente o in formato diverso da quello fornito dal Comitato organizzatore.",
      "Il mancato rispetto di tale norma prevede una multa pari ad € 20.00 Al termine dell’incontro, i Responsabili di entrambe le compagini sono tenuti a richiedere al Direttore di Gara, nei termini previsti, la terza copia della propria lista, sulla quale dovranno risultare il “Rapportino di gara” e le relative annotazioni concernenti i gol realizzati, le sanzioni disciplinari comminate e i relativi voti. Qualora il Responsabile riscontri eventuali discordanze rispetto a quanto effettivamente verificatosi nel corso dell’incontro appena concluso, sarà tenuto a contestarle immediatamente al Direttore di Gara, richiedendone, ove ne ricorrano i presupposti, la verifica e l’eventuale rettifica prima di lasciare il campo sportivo.",
      "Dal momento in cui il risultato sarà omologato ed online nella piattaforma di Enjore relativa ai campionati: ENJORE:https://asicalciolazio.enjore.com/it",
      "DECORSO TALE TERMINE, NON SARÀ PIÙ AMMESSA ALCUNA RICHIESTA DI VARIAZIONE,A QUALSIASI TITOLO.",
      "Qualora uno o entrambi i Responsabili non provvedano a richiedere il “Rapportino di gara”, si intenderanno integralmente applicabili, a tutti gli effetti, le disposizioni di cui al punto precedente.",
      "## INIZIO E PROSECUZIONE DELLA GARA",
      "Le squadre non potranno dare inizio alla gara con un numero di giocatori inferiore a nove. In caso contrario, alla squadra inadempiente sarà attribuita la sconfitta a tavolino con il risultato di 0-3, nonché la penalizzazione di un punto nella classifica generale.",
      "Una volta regolarmente iniziata la gara, la stessa potrà proseguire qualora una squadra disponga di almeno sette giocatori in campo.",
      "## UTILIZZO DEI CALCIATORI",
      "Una volta iniziato il Campionato e/o le singole gare, le squadre non potranno utilizzare calciatori non regolarmente inseriti nella lista dei 40 giocatori presentata dal Dirigente Responsabile.",
      "La violazione di tale disposizione comporterà l’annullamento della gara e l’attribuzione della vittoria a tavolino alla squadra avversaria con il risultato di 0-3, nonché la penalizzazione di un punto nella classifica generale.",
      "Qualora un calciatore partecipi alla gara utilizzando una falsa identità ovvero esibendo un documento contraffatto o alterato, il medesimo sarà passibile delle ulteriori responsabilità e delle sanzioni previste dalla normativa vigente, fatto salvo ogni ulteriore provvedimento di competenza degli organi preposti.",
      "## SOSTITUZIONI",
      "Le sostituzioni potranno essere effettuate in maniera multipla e ripetitiva, a gioco fermo e senza distinzione di ruolo, purché effettuate secondo le modalità previste dal presente Regolamento.",
      "Nel corso del primo tempo potranno essere effettuate un massimo di 3 sostituzioni. Durante l’intervallo potranno essere effettuate sostituzioni in numero illimitato. Nel corso del secondo tempo potranno essere effettuate ulteriori 7 sostituzioni.",
      "## SOSTITUZIONI DELLA SQUADRA AVVERSARIA",
      "Qualora una squadra proceda a effettuare una o più sostituzioni, anche la squadra avversaria sarà autorizzata a effettuare contestualmente le proprie sostituzioni, nel rispetto delle modalità previste dal presente Regolamento.",
      "## MODALITÀ DI EFFETTUAZIONE DELLE SOSTITUZIONI",
      "Salvo diversa disposizione o specifica autorizzazione del Direttore di Gara, l’ingresso del calciatore sostituto dovrà avvenire in corrispondenza della linea mediana del terreno di gioco, a gioco fermo e solamente dopo che il calciatore sostituito abbia completamente abbandonato il terreno di gioco.",
      "L’ingresso del calciatore sostituto sarà consentito esclusivamente previa autorizzazione del Direttore di Gara.",
      "Il mancato rispetto delle suddette disposizioni comporterà l’ammonizione del calciatore che abbia effettuato l’ingresso irregolare, fatta salva ogni ulteriore sanzione eventualmente prevista dal presente Regolamento."
    ]
  },
  {
    "id": "art-10",
    "label": "Art. 10",
    "title": "Sanzioni disciplinari",
    "blocks": [
      "## PROVVEDIMENTI DISCIPLINARI",
      "Le sanzioni disciplinari sono deliberate dagli Organi competenti e comunicate mediante apposito Comunicato Ufficiale al termine di ciascuna giornata di Campionato.",
      "Le squadre partecipanti e il Comitato Organizzatore richiedono e garantiscono la massima fermezza nei confronti di qualsiasi comportamento aggressivo, intimidatorio, minaccioso o comunque contrario ai principi di correttezza e lealtà sportiva, posto in essere da qualsiasi tesserato.",
      "## ESPULSIONI E AMMONIZIONI",
      "In caso di espulsione, il calciatore o il dirigente non potrà, in via automatica, partecipare alla gara immediatamente successiva prevista dal calendario, in attesa del provvedimento del Giudice Sportivo.",
      "In caso di ammonizioni maturate in gare differenti, al raggiungimento della terza ammonizione il calciatore sarà automaticamente squalificato per la gara successiva. Le squalifiche e gli ulteriori provvedimenti disciplinari adottati dal Giudice Sportivo saranno pubblicati a cura del Comitato Organizzatore mediante apposito Comunicato Ufficiale.",
      "## PARTECIPAZIONE DI CALCIATORI SQUALIFICATI",
      "È fatto assoluto divieto a un calciatore squalificato di prendere parte a una gara durante il periodo di squalifica.",
      "L’eventuale violazione di tale disposizione comporterà la sconfitta a tavolino della squadra di appartenenza con il risultato di 0-3, nonché la penalizzazione di un punto nella classifica generale. In aggiunta, la squalifica residua del calciatore interessato sarà raddoppiata, salvo ulteriori provvedimenti adottati dal Giudice Sportivo.",
      "È altresì fatto assoluto divieto ai calciatori, dirigenti e collaboratori squalificati di accedere o permanere all’interno del recinto di gioco in occasione delle gare del Campionato. In caso di violazione di tale disposizione, saranno comminate una giornata di squalifica al Capitano e una giornata di squalifica all’Allenatore della squadra coinvolta, fatta salva ogni ulteriore sanzione prevista dal presente Regolamento.",
      "Le squalifiche superiori a tre giornate potranno, sulla base di specifica decisione del Giudice Sportivo, essere estese anche alle altre competizioni organizzate sotto l’egida ASI.",
      "Qualora un calciatore partecipi contemporaneamente a più Campionati o manifestazioni ASI, l’eventuale estensione della squalifica alle ulteriori competizioni sarà efficace esclusivamente qualora sia espressamente indicata nel relativo Comunicato o provvedimento del Giudice Sportivo.",
      "## AGGRAVAMENTO DELLE SANZIONI",
      "In relazione alla gravità dei fatti e sulla base di quanto riportato nel referto arbitrale, il Giudice Sportivo potrà disporre un ulteriore inasprimento della sanzione.",
      "Il tesserato di una squadra partecipante, sia esso calciatore, dirigente o collaboratore, che ponga in essere comportamenti non conformi ai principi di correttezza, lealtà e disciplina sportiva, anche al di fuori del recinto di gioco, potrà essere sottoposto a procedimento disciplinare sulla base del referto arbitrale ovvero delle relazioni redatte dagli Organizzatori, dai Commissari di Campo o dagli Osservatori Arbitrali.",
      "Il calciatore che, nel corso di una gara, riceva esclusivamente un’ammonizione sarà soggetto a squalifica al raggiungimento della terza ammonizione.",
      "Qualora un calciatore già ammonito o in posizione di diffida venga espulso nel corso della gara, per doppia ammonizione o per espulsione diretta, la squalifica conseguente all’espulsione non estingue, non assorbe e non sana la posizione disciplinare preesistente del calciatore, che resterà pertanto integralmente valida ai fini del computo delle successive sanzioni.",
      "Se i Campionati, Tornei e/o Coppe dovessero proseguire dopo la prima fase con ulteriori fasi, si applicheranno le seguenti disposizioni:- Le fasi successive alla prima, comprese eventuali gare ad eliminazione diretta, semifinali e finali, costituiscono una prosecuzione della fase iniziale e pertanto sono parte integrante della medesima manifestazione sportiva considerata;- Quindi che le sanzioni disciplinari comminate durante la prima fase NON saranno azzerate e continueranno a produrre i loro effetti nelle fasi successive.",
      "## GIUDICE SPORTIVO E PROVVEDIMENTI DISCIPLINARI",
      "Sulla base dei referti arbitrali e degli ulteriori atti ufficiali acquisiti, il Giudice Sportivo ASI, Avv. Paolo Piacente, provvederà all’adozione delle sanzioni disciplinari relative ai singoli calciatori, alle squadre e alle gare.",
      "Il Giudice Sportivo provvederà altresì all’omologazione dei risultati delle gare oggetto di ricorsi, reclami, mancata presentazione, rinuncia o altre irregolarità.",
      "## RICORSI E RECLAMI",
      "I ricorsi e i reclami privi di motivazione, non sottoscritti dal Dirigente Responsabile o redatti in forma generica e non sufficientemente circostanziata saranno dichiarati inammissibili.",
      "Ogni ricorso o reclamo dovrà essere corredato dal versamento della tassa-reclamo pari a € 50,00, da effettuarsi presso ASI Comitato Provinciale entro e non oltre 24 ore dalla presentazione del preavviso di reclamo.",
      "Copia della ricevuta del versamento dovrà essere trasmessa ai seguenti indirizzi: info@asiroma.org stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com Al termine della gara, il preavviso di ricorso dovrà essere specificato dal dirigente della società sul modulo di refertazione gara. La squadra avversaria dovrà essere avvisata di tale preavviso di ricorso attraverso una comunicazione scritta inviata al Responsabile della società avversaria tramite email entro le ventiquattro ore successive. Il ricorso completo dovrà essere presentato entro e non oltre le 24 ore successive alla conclusione della gara. Qualora il ricorso venga accolto, anche parzialmente, la tassa-reclamo sarà restituita alla società ricorrente.",
      "## RICORSO IN APPELLO",
      "Il ricorso in appello dovrà essere sottoscritto dal Responsabile e/o dal Capitano della squadra interessata e dovrà essere presentato entro e non oltre le 24 ore successive alla pubblicazione del provvedimento del Giudice Sportivo.",
      "Il provvedimento del Giudice Sportivo sarà pubblicato entro le ore 16:00 del sabato successivo alla gara, salvo diversa disposizione del Comitato Organizzatore. L’esito del ricorso in appello sarà comunicato agli interessati entro 48 ore dalla presentazione dello stesso.",
      "Avverso i provvedimenti del Giudice Sportivo è ammesso ricorso in appello da parte delle società interessate, mediante istanza scritta indirizzata alla Commissione Disciplinare.",
      "Le decisioni assunte dalla Commissione Disciplinare in secondo grado saranno da considerarsi definitive, insindacabili e inappellabili nell’ambito delle competizioni disciplinate dal presente Regolamento.",
      "## REGOLE DI GIOCO E COMPORTAMENTO",
      "Per quanto concerne le ulteriori Regole del Gioco e la giustizia sportiva, si applicano le disposizioni vigenti nelle competizioni organizzate sotto l’egida dell’ASI e della FIGC salvo quanto espressamente previsto e disciplinato dal presente Regolamento.",
      "Per quanto concerne il linguaggio blasfemo, alla prima violazione sarà comminata l’ammonizione.",
      "In caso di successiva bestemmia ovvero qualora la bestemmia sia accompagnata da proteste, ingiurie o atteggiamenti irriguardosi nei confronti dei Direttori di Gara, sarà comminata l’espulsione diretta, fatta salva ogni ulteriore sanzione disciplinare prevista.",
      "## CARTELLINO VERDE – FAIR PLAY",
      "I Direttori di Gara saranno dotati anche di un cartellino verde, destinato esclusivamente a premiare e segnalare comportamenti, gesti o iniziative di particolare valore sotto il profilo del fair play, della correttezza e della lealtà sportiva. L'utilizzo del cartellino verde non comporterà alcuna conseguenza disciplinare e avrà esclusivamente finalità di riconoscimento e valorizzazione dei comportamenti virtuosi."
    ]
  },
  {
    "id": "art-11",
    "label": "Art. 11",
    "title": "Varie",
    "blocks": [
      "## RESPONSABILITÀ PER DANNI E INFORTUNI",
      "Il Comitato Organizzatore declina ogni responsabilità per eventuali danni, infortuni o altri eventi lesivi verificatisi prima, durante o dopo lo svolgimento delle gare, a carico di atleti, dirigenti, collaboratori e terzi, ovvero cagionati dai medesimi, fatto salvo quanto espressamente previsto dalle coperture assicurative stipulate per il tramite dell’affiliazione e del tesseramento ASI.",
      "## RESPONSABILITÀ DELLE SOCIETÀ E DEI DIRIGENTI",
      "Ciascuna rappresentativa, per il tramite del proprio Dirigente Responsabile, è direttamente responsabile della veridicità, completezza e correttezza delle dichiarazioni e dei dati riportati nella distinta di gara. L’eventuale indicazione di dati falsi, inesatti, incompleti o non corrispondenti al vero comporterà l’adozione dei provvedimenti previsti dal presente Regolamento, fatta salva ogni ulteriore responsabilità prevista dalla normativa vigente.",
      "## CONDOTTE GRAVI E PROVVEDIMENTI DI ESCLUSIONE",
      "Qualsiasi comportamento grave, oltraggioso, violento, minaccioso o comunque contrario ai principi di correttezza, lealtà ed etica sportiva, posto in essere sia durante lo svolgimento delle gare sia nell’ambito della manifestazione, potrà comportare l’immediata sospensione o esclusione dei soggetti responsabili dalla partecipazione alle gare successive, nonché il divieto di assistere alle gare della propria squadra all’interno del recinto di gioco.",
      "Il Comitato Organizzatore, indipendentemente dagli eventuali provvedimenti disciplinari già adottati dagli Organi competenti, si riserva la facoltà di disporre l’allontanamento definitivo dal Campionato dei singoli partecipanti e, ove ne ricorrano i presupposti, dell’intera rappresentativa.",
      "## MANCATA DISPUTA DELLA GARA",
      "La squadra che risulti responsabile della mancata disputa di una gara per cause ad essa imputabili, qualora tale circostanza non venga comunicata al Comitato Organizzatore in tempo utile per consentire l’eventuale rinvio, e comunque entro e non oltre 48 ore antecedenti l’orario previsto per il calcio d’inizio, sarà tenuta al pagamento integrale della quota relativa all’affitto del campo di gioco. Tale obbligo sussisterà anche nel caso in cui la squadra responsabile della mancata disputa rivesta il ruolo di squadra ospite.",
      "## MODIFICHE E INTEGRAZIONI AL REGOLAMENTO",
      "Qualora, nel corso della manifestazione, si renda necessario intervenire a seguito dell’emersione di eventuali lacune, incongruenze o necessità di adeguamento normativo, il Comitato Organizzatore si riserva la facoltà di apportare al presente Regolamento le modifiche e integrazioni ritenute necessarie. Il Comitato Organizzatore si riserva altresì, nel rispetto delle disposizioni applicabili, la facoltà di procedere alla selezione e/o all’ammissione dei partecipanti, siano essi singoli calciatori o squadre, sia anteriormente all’inizio della manifestazione sia nel corso della stessa.",
      "## NORME DI RINVIO",
      "Per ogni controversia, contestazione o fattispecie non espressamente disciplinata dal presente Regolamento, si farà riferimento, per quanto applicabile e compatibile, alle disposizioni contenute nei regolamenti vigenti dell’ASI e della F.I.G.C."
    ]
  },
  {
    "id": "art-12",
    "label": "Art. 12",
    "title": "Responsabilità ed assicurazioni",
    "blocks": [
      "## RESPONSABILITÀ E COPERTURA ASSICURATIVA",
      "L’Organizzazione non risponde, nei limiti consentiti dalla normativa vigente, dei danni, infortuni o lesioni arrecati a persone e/o cose che si verifichino in occasione dello svolgimento del Torneo, qualora tali eventi non siano imputabili a responsabilità diretta dell’Organizzazione stessa.",
      "Il Torneo ha carattere esclusivamente ricreativo e amatoriale. Con la sottoscrizione della lista di iscrizione, ciascun partecipante dichiara di essere consapevole della natura e delle caratteristiche della manifestazione, nonché dei rischi connessi alla pratica dell’attività sportiva, assumendosi le responsabilità derivanti dalla propria partecipazione, nei limiti previsti dalla legge.",
      "La copertura assicurativa prevista per i partecipanti decorrerà a partire dal giorno STESSO della data di consegna della documentazione necessaria e del contestuale pagamento del relativo costo.",
      "Pertanto, in assenza della completa consegna della documentazione richiesta e del pagamento della quota assicurativa, non potrà ritenersi perfezionata alcuna copertura assicurativa a favore del partecipante.",
      "L’Organizzazione non potrà essere ritenuta responsabile per eventuali eventi verificatisi anteriormente alla decorrenza effettiva della copertura assicurativa."
    ]
  },
  {
    "id": "art-13",
    "label": "Art. 13",
    "title": "Esclusioni dai campionati",
    "blocks": [
      "## CONDOTTE VIOLENTE, INTIMIDATORIE E COMMISSARIO DI CAMPO",
      "Il calciatore che si renda responsabile di atti di violenza, minaccia, intimidazione, aggressione o di qualsiasi altra condotta gravemente lesiva nei confronti del Direttore di Gara, degli avversari, dei dirigenti, degli altri tesserati o del pubblico, sarà immediatamente allontanato dalla manifestazione, fatta salva l’adozione degli ulteriori provvedimenti disciplinari di competenza degli Organi preposti.",
      "Qualora più calciatori appartenenti alla medesima squadra si rendano protagonisti di condotte analoghe, il Comitato Organizzatore, valutata la gravità dei fatti e sentiti gli Organi competenti, potrà disporre l’esclusione della squadra dal Torneo, senza che alla stessa o ai suoi tesserati possa essere riconosciuto alcun rimborso delle quote eventualmente versate.",
      "Nel corso delle gare potrà essere disposta la presenza di un Commissario di Campo, incaricato di vigilare sul regolare svolgimento della manifestazione e di segnalare eventuali comportamenti o fatti rilevanti ai fini disciplinari.",
      "Il Commissario di Campo avrà facoltà di redigere apposito rapporto o referto e di collaborare, ove necessario, con il Direttore di Gara, fornendo allo stesso ogni informazione utile ai fini della corretta gestione dell’incontro.",
      "Resta espressamente stabilito che ogni decisione relativa allo svolgimento della gara, all’applicazione delle Regole del Gioco e ai provvedimenti da adottare durante l’incontro è di esclusiva competenza del Direttore di Gara, ferme restando le successive valutazioni e determinazioni degli Organi disciplinari competenti."
    ]
  },
  {
    "id": "art-14",
    "label": "Art. 14",
    "title": "Legge sulla privacy",
    "blocks": [
      "## TRATTAMENTO DEI DATI PERSONALI",
      "Tutti i partecipanti agli eventi e alle manifestazioni sportive organizzate dall’A.S.I. – Comitato Provinciale di Roma, con la sottoscrizione della documentazione di iscrizione e/o partecipazione, prendono atto del trattamento dei propri dati personali e, ove necessario, prestano il relativo consenso, nei limiti e secondo le modalità previste dalla normativa vigente in materia di protezione dei dati personali, ai sensi del Regolamento (UE) 2016/679 (GDPR) e del D.Lgs. 30 giugno 2003, n. 196, come successivamente modificato e integrato.",
      "I dati personali saranno trattati esclusivamente per finalità connesse alla gestione, organizzazione e svolgimento delle attività sportive, associative e istituzionali dell’Ente, nonché per gli adempimenti amministrativi, assicurativi e regolamentari connessi alla partecipazione alle manifestazioni.",
      "Gli interessati potranno esercitare i diritti riconosciuti dalla normativa vigente, ivi compresi, ove applicabili, il diritto di accesso, rettifica, aggiornamento, cancellazione, limitazione del trattamento, opposizione e revoca del consenso, secondo le modalità previste dalla legge e dall’informativa sul trattamento dei dati personali.",
      "L’esercizio dei suddetti diritti dovrà essere effettuato mediante comunicazione scritta indirizzata al soggetto titolare o responsabile del trattamento, secondo i recapiti e le modalità indicati nell’informativa privacy fornita agli interessati.",
      "Il trattamento dei dati personali sarà effettuato nel rispetto dei principi di liceità, correttezza, trasparenza, minimizzazione, sicurezza e riservatezza previsti dalla normativa vigente.",
      "Per quanto concerne l’individuazione del Titolare del trattamento, del Responsabile del trattamento e degli eventuali ulteriori soggetti autorizzati o designati, si farà riferimento alla relativa informativa privacy adottata dall’A.S.I. – Comitato Provinciale di Roma."
    ]
  },
  {
    "id": "art-15",
    "label": "Art. 15",
    "title": "Maltempo, eventi particolari e recuperi",
    "blocks": [
      "In caso di condizioni meteorologiche avverse o di altre circostanze particolari che possano far presumere il mancato svolgimento della gara, le squadre sono comunque tenute a presentarsi presso il terreno di gioco, munite di tutto il necessario per poter regolarmente disputare l’incontro.",
      "La decisione in merito alla disputa della gara ovvero alla sua sospensione o rinvio a data da destinarsi sarà assunta dal Direttore di Gara, di concerto con il Comitato Organizzatore e, ove necessario, sentiti i Capitani delle squadre interessate, fermo restando che la decisione finale in ordine allo svolgimento della gara compete al Direttore di Gara.",
      "La squadra che, a causa delle condizioni meteorologiche avverse, ometta di presentarsi presso il terreno di gioco con un organico e l’equipaggiamento necessari per poter disputare l’incontro sarà soggetta alle sanzioni e alle penalità previste nel presente Regolamento.",
      "In caso di interruzione della gara dovuta a una temporanea interruzione dell’energia elettrica, ciascuna interruzione potrà avere una durata massima di 15 minuti e potrà verificarsi per un massimo di due volte nel corso della medesima gara.",
      "Qualora si verifichi una terza interruzione consecutiva dell’energia elettrica, tale da impedire la regolare prosecuzione dell’incontro, la gara sarà definitivamente sospesa, salvo diversa determinazione del Direttore di Gara qualora sussistano le condizioni per la ripresa del gioco.",
      "Qualora la gara venga definitivamente interrotta prima dell’inizio del 15° minuto del secondo tempo, il risultato maturato fino a quel momento sarà annullato e l’incontro dovrà essere recuperato integralmente, secondo modalità, data e orario stabiliti dal Comitato Organizzatore.",
      "Qualora, invece, l’interruzione definitiva avvenga a partire dal 15° minuto del secondo tempo, si applicheranno le disposizioni previste dagli Organi competenti in materia di omologazione della gara e determinazione del relativo risultato."
    ]
  },
  {
    "id": "art-16",
    "label": "Art. 16",
    "title": "Partita pro-forma e VAR",
    "blocks": [
      "Qualora il Direttore di Gara, a causa di minacce, intimidazioni, pressioni o di qualsiasi altra situazione tale da compromettere la propria libertà di giudizio e/o da determinare un concreto timore per la propria incolumità o per quella degli altri soggetti presenti, ritenga di non poter dirigere l’incontro nelle normali condizioni di autonomia e sicurezza, potrà disporre, ove ne ricorrano i presupposti, la prosecuzione della gara “pro-forma”.",
      "In tale circostanza, il Direttore di Gara dovrà riportare dettagliatamente nel proprio referto ufficiale tutti i fatti, gli episodi e le circostanze verificatisi, affinché gli Organi di Giustizia Sportiva possano procedere alle opportune valutazioni e assumere i provvedimenti di propria competenza.",
      "## SERVIZIO V.A.R.",
      "In occasione di alcune gare potrà essere previsto l’utilizzo del servizio V.A.R., secondo le modalità operative e il relativo protocollo di applicazione adottato dall’A.S.I. S.S. per la stagione sportiva 2026/2027 Il servizio V.A.R. potrà essere richiesto espressamente dalle squadre interessate, compatibilmente con la disponibilità del Tecnico V.A.R. e del Direttore di Gara V.A.R.",
      "La richiesta dovrà essere presentata al Comitato Organizzatore con un preavviso di almeno 7 giorni rispetto alla data prevista per la gara.",
      "L’attivazione del servizio comporterà, a carico della squadra richiedente, il pagamento di un contributo pari a € 100,00, da corrispondere secondo le modalità stabilite dal Comitato Organizzatore.",
      "L’eventuale indisponibilità del personale tecnico o arbitrale necessario costituisce motivo ostativo all’attivazione del servizio, senza che ciò possa determinare alcuna responsabilità a carico del Comitato Organizzatore."
    ]
  },
  {
    "id": "art-17",
    "label": "Art. 17",
    "title": "Contatti utili",
    "blocks": [
      "Il Referente Tecnico-Organizzativo del Torneo è il Sig. Dario PORRETTA, reperibile al numero 347.8172305, dalle ore 18:30 alle ore 21:00.",
      "Il Collaboratore incaricato dei rapporti con i Responsabili delle squadre è il Sig. Stefano SABATINI, reperibile al numero 347.0552160, dalle ore 15:00 alle ore 20:00.",
      "Il Responsabile Organizzativo del Settore Calcio – Regione Lazio è il Sig. Americo SCATENA, reperibile al numero 347.7090000.",
      "Il Sig. Umberto AIUTIERI, Responsabile della Segreteria dell’ASI – Comitato Provinciale di Roma, potrà essere contattato esclusivamente ai numeri 06.99701564 e 06.88979908, dal lunedì al venerdì, nelle seguenti fasce orarie: 10:00–13:00 e 15:00–18:00.",
      "## COMUNICAZIONI UFFICIALI",
      "Tutte le comunicazioni, istanze, richieste e/o segnalazioni indirizzate al Comitato ASI dovranno essere effettuate esclusivamente per iscritto, mediante posta elettronica, ai seguenti indirizzi:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "Le comunicazioni effettuate attraverso modalità differenti da quelle sopra indicate non potranno essere considerate, salvo diversa ed espressa disposizione del Comitato Organizzatore, quali comunicazioni ufficiali ai fini dell’applicazione del presente Regolamento."
    ]
  },
  {
    "id": "art-18",
    "label": "Art. 18",
    "title": "Premiazioni",
    "blocks": [
      "Al termine del Campionato sarà organizzata la cerimonia ufficiale di premiazione, che si svolgerà presso la località individuata e comunicata dal Comitato Organizzatore.",
      "È vivamente raccomandata la più ampia partecipazione possibile da parte dei Responsabili e dei rappresentanti di tutte le squadre partecipanti, al fine di garantire la piena condivisione e valorizzazione del momento conclusivo della manifestazione.",
      "I premi predisposti e assegnati alle squadre e/o ai singoli partecipanti che non vengano ritirati dai rispettivi Responsabili in occasione della cerimonia ufficiale di premiazione saranno trattenuti dal Comitato Organizzatore.",
      "La mancata partecipazione alla cerimonia di premiazione e il conseguente mancato ritiro dei premi potranno essere valutati dal Comitato ASI Roma ai fini dell’ammissione e/o della partecipazione della squadra alla successiva edizione del Campionato, fatta salva ogni diversa determinazione del Comitato Organizzatore."
    ]
  },
  {
    "id": "iscr",
    "label": "Iscr.",
    "title": "Iscrizione S.S. 2026/2027",
    "blocks": [
      "## TERMINI E MODALITÀ DI ISCRIZIONE",
      "L’iscrizione al Campionato dovrà essere perfezionata entro e non oltre il 17 settembre 2026 e comporterà il versamento della relativa quota di iscrizione, nonché della quota prevista per l’affiliazione della società all’ASI – Comitato Provinciale di Roma.",
      "Il tesseramento dei propri dirigenti e calciatori dovrà essere completato entro e non oltre il 30 settembre 2026.",
      "Le ricevute relative a tutti i bonifici effettuati per il Campionato dovranno essere tassativamente trasmesse entro due giorni dalla disposizione del bonifico alla propria banca, ai seguenti indirizzi di posta elettronica:",
      "info@asiroma.org - stefano.sabatini@arbitrisportitaliani.it - americo.scatena@gmail.com - torneiasicalciolazio@gmail.com",
      "La mancata trasmissione della documentazione entro i termini stabiliti potrà comportare la sospensione delle relative procedure amministrative e/o l’adozione dei provvedimenti previsti dal Regolamento del Campionato.",
      "Il modulo da compilare e firmare è disponibile solo nel PDF ufficiale."
    ]
  },
  {
    "id": "accr",
    "label": "Acc.",
    "title": "Accettazione del regolamento",
    "blocks": [
      "Il/La sottoscritto/a dichiara di aver ricevuto, letto e integralmente esaminato il Regolamento del Campionato, composto da 18 (diciotto) articoli e 31 (trentuno) pagine, compresa la presente, e di accettarne senza riserva tutte le disposizioni, gli obblighi, le procedure e le sanzioni in esso contenuti.",
      "Il modulo da compilare e firmare è disponibile solo nel PDF ufficiale."
    ]
  },
  {
    "id": "allegato-1",
    "label": "All. 1",
    "title": "Allegato n.1 – Arti&Mestieri",
    "blocks": [
      "Campionato Over 35 “Arti&Mestieri” – Stagione Sportiva 2026/2027 – Inizio 19/10/2026.",
      "## Art. 1 – Partecipazione Portiere",
      "Possono ricoprire il ruolo di portiere gli atleti che abbiano compiuto il venticinquesimo anno di età. Essi possono giocare solo nel ruolo di portiere se di età inferiore ai ventinove anni già compiuti.",
      "## Art. 2 – Spostamenti Gara",
      "Si invitano le Società a concedere gli spostamenti gara qualora gli stessi, per validi e comprovati motivi, vengano richiesti con almeno 30 (trenta) giorni di anticipo rispetto alla data ufficiale.",
      "## Art. 3 – Fuoriquota",
      "È consentito inserire in distinta di gara n. 5 (cinque) atleti fuoriquota, di età inferiore di massimo sei anni rispetto alla categoria (29 anni già compiuti), di cui n. 3 (tre) contemporaneamente in campo. L'eventuale portiere fuoriquota NON rientra nel computo dei tre atleti impiegabili; pertanto, saranno ammessi in campo n. 3 (tre) fuoriquota di movimento più il portiere.",
      "## Art. 4 – Sanzioni Amministrative",
      "Il ritardo nella consegna della distinta di gara - che dovrà essere corretta in ogni sua parte e redatta in triplice copia - agli ufficiali di gara, qualora avvenga oltre i venti minuti antecedenti l'orario ufficiale d'inizio, nonché l'assenza delle apposite fascette identificative per gli atleti fuoriquota, saranno sanzionati con ammenda pari a € 10,00 per ciascuna infrazione. Detta ammenda dovrà essere versata alla terna arbitrale prima dell'inizio della gara successiva.",
      "L'importo così raccolto confluirà nella donazione che i Campionati ASI Calcio Lazio, nell'ambito dell'iniziativa \"Arti&Mestieri\", effettueranno a fine stagione a favore di una Onlus benefica.",
      "## Art. 5 – Formula di Svolgimento",
      "Il campionato si svolgerà con la formula girone all’italiana con gare di sola andata. Al termine di questa fase ci sarà una divisione tra le prime quattro squadre classificate e le squadre classificate tra il quinto e l’ottavo posto. Poi ci saranno due minicampionati con girone all’italiana ma con gare di A/R.",
      "La prima classificata del girone con solo andata vincerà un trofeo e le vincitrici, arrivate prime nei due successivi mini-gironi vinceranno altresì, ciascuno, un trofeo. Inoltre, verranno premiati il miglior giocatore, il capocannoniere del campionato ed il miglior portiere ed il giocatore fair play dei soli due mini-gironi.",
      "## Art. 6 – Premiazioni",
      "Verrà premiata la Società vincitrice del Campionato. A tutte le altre Società partecipanti verrà consegnato un trofeo di partecipazione. Saranno inoltre assegnati i seguenti riconoscimenti individuali: Miglior Giocatore, Capocannoniere del Campionato e Miglior Portiere della manifestazione.",
      "## Art. 7 – Finestra di Mercato",
      "La finestra di mercato è prevista dal 01/02/2027 al 28/02/2027 fino al raggiungimento dei 40 nominativi.",
      "## Art. 8 – Donazione Benefica",
      "La donazione benefica di fine stagione è da considerarsi obbligatoria per ciascuna squadra partecipante e con un minimo di quattrocento euro, salvo difficoltà oggettive sopravvenute. Onlus beneficiaria ancora da definire.",
      "## Art. 9 – Eccezioni di giocatori ESTERNI",
      "Possono essere utilizzati degli esterni per un massimo di due. Eccezione per Iannaccone Ass. che potrà utilizzarne sei per storicità nel gruppo. Gli esterni non possono essere degli under. Altre eccezioni per i Veterinari che hanno un neolaureato nella professione di venticinque anni e per un giocatore dei VV.F. che compirà 29 anni entro il 2026.",
      "## Art. 10 – Rappresentativa",
      "Il C.O. si impegna a costituire una “Rappresentativa di A&M 2026/2027” con tre convocati per ciascuna società partecipante (di cui uno dovrà essere il responsabile di ciascuna squadra partecipante) per svolgere un’amichevole con altra realtà sportiva e magari inserirla in un evento legato all’aspetto benefico del campionato."
    ]
  }
]
